name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify your desired Java version
          distribution: 'adopt'

      - name: Grant executable permission for gradlew
        run: chmod +x gradlew  # Make sure gradlew is executable

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Package the application
        run: ./gradlew bootJar  # For Spring Boot applications

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: spring-boot-app
          path: build/libs/*.jar  # Adjust if your JAR is in a different location
