name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  
          distribution: 'adopt'

      - name: Grant executable permission for gradlew
        run: chmod +x gradlew  # Make sure gradlew is executable

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Package the application
        run: ./gradlew bootJar  

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: spring-boot-app
          path: build/libs/*.jar  
